-   id: pg_format
    name: pg_format
    description: PreCommit hook to format PostgreSQL code using pgFormatter
    entry: pg_format -i -L
    language: system
    types: [sql]
    minimum_pre_commit_version: '0'